### ISSUE TITLE
echarts5.0 error

### ISSUE THREAD

**Issue by Dreamagician** [ecomfe/echarts-gl#416]
n.helper.completeDimensions is not a function

**Comment by djzhao627** [comment]
@Dreamagician Change the echarts-gl version will fix this issue, for example 2.0.7 works well in cehcarts 5.51.1
